## 1st July 2026

# Introduction to Machine Learning.     
## 1. What is machine Learning?    
Machine learning is a branch of AI that allows computers to learn patterns from data and make predictions or decisions without being explicitly programmed for every rule.       
Instead of writing fixed instructions, we give the computer data, and it learns relationships from that data.     

_Example_      
Instead of manually writing rules to determine house rent in Nairobi, we can train a machine learning model using previous housing data.. The model can learn how factors such as estate, property type, number of bedrooms, house size, availabililty of parking, and the distance to cbd influence rent prices.     

|Estate. |Bedrooms|House size(sqm)|Parking|Monthly Rent |
|------  |--------|---------------|-------|-------------|
|Kasarani|2       |80             |No     |25,000       |
|Karen   |4       |220            |Yes    |250,000      |
|Kilimani|3       |150            |Yes    |120,000      |    

A machine learning model can study this data and learn that:     
- Houses i high end estates usually have higher rent.    
- More bedrooms often increase rent.    
- Bigger houses may lead to higher rent.   
- Parking availability can affect price.      

After learning from past data, the model can predict rent for a new house.  

__Real World applications of machine learning__       
- ___Finance and banking:___ Banks use machine learning to:
    Detect Fraud.        
    Predict loan default.   
    Score credit worthiness.  
    Recommended bank products.    
    _Example_ A bank may predict whether a customer is likely to repay a loan based on income, employment status, loan history.    
- ___Healthcare:___ Hospitals and research institutions use machine learning to:   
    - Predict disease risk.   
    - Detect diseases from images(cancer prediction from image scans).  
    - Recommending treatment plans.     
    _Example_ A model can help predict whether a patient is at a higher risk of diabetes using age, height, weight, bmi, blood pressure, glucose level and family history.    
- ___Ecommerce:___ Online stores use machine learning to:   
    - Recommend products.   
    - Predict customer churn.   
    - Personalized adverts.  
    - Forecast sales.   
    _Example_ Ecommerce platforms such as Jumia or Amazon can recommend products based off what a user has searched for, viewed or bought before.    

- ___Transport/Logistics:___ Transport companies use machine learning to:    
    - Predict traffic.   
    - Estimate delivery time.  
    - Optimize routes.  
    - Detect unsafe driving behaviour.  
    _Example_ Google maps uses machine to estimate travel time based on traffic patterns and previous route data.   

## Types of Machine Learning. 
- 1. Supervised learning.  
- 2. Unsupervised learning.  
- 3. Reinforcement learning.    

### 1. Supervised learning. 
This is a type of machine learning where the model learns from labelled data.  
Labelled data s a dataset that already contains the corrrect answer.   

_Example_    
|Estate  |Bedrooms|House size(sqm)|Parking|Monthly Rent |
|------  |--------|---------------|-------|-------------|
|Kasarani|2       |80             |No     |25,000       |
|Karen   |4       |220            |Yes    |250,000      |
|Kilimani|3       |150            |Yes    |120,000      |   

Here:    
__Features:__ Estate, Bedrooms, House Size(sqm), Parking.       
__Label:__ Monthly Rent.      

The model learns the relationship between the features and the label.       
Common supervised learning tasks:     
- __Regression:__ Regression is used when the target variable is numeric. e.g. predicting house rent, predicting salary, predicting sales revenue, predicting student examp score.       

- __Classification:__ Classification is used when the target variable is a category. e.g. predicting if whether a customer will default: Yes or No, predicting whether an email is spam or not spam, predicting whether a student will pass or fail.   

### 2. Unsupervised learning.    
Unsupervised learning is used when the dataset does not have a labelled answer.    
The model tries to discover hidden patterns, groups, or structures in the data by itself.     

_Example_     
Assume we have the housing data with estate, rent, house size, bedrooms, distance to cbd but we do not give the model the target column to predict.   
The model may group houses into clusters such as:   
* Budget houses.   
* Middle income houses 
* Luxury Houses.  

__Common categories in Unsupervised learning__     
- __Clustering:__ Clustering means grouping similar records togethe.    
_Example_     
The model may group houses into clusters such as:   
* Budget houses.   
* Middle income houses 
* Luxury Houses.    

- __Dimensionality reduction:__ Dimensionality reduction reduces many columns into fewer important components while still preserving useful information.     
It is uselful when a dataset has many columns.      

_Example_    
Reducing many housing features into fewer property quality indicators.    

### 3. Reinforcement learning.    
Reinforcement learning is a type of machine learning where a model learns by interacting with enviroment.       
The agent takes actions and recieves penalties or rewards.    

## Concepts of machine learning.   
### Features    
Features are the input variables used by the model to make predictions.    
### Label/Target.  
A label/target is a the target variable used by the models to make predictions.    
### Training data.   
Training data is the portion of the dataset used to teach/trai the machine learning model.    
The model studies this data and learns patterns from it.   

_Example_    
|Estate  |Bedrooms|House size(sqm)|Parking|Monthly Rent |
|------  |--------|---------------|-------|-------------|
|Kasarani|2       |80             |No     |25,000       |
|Karen   |4       |220            |Yes    |250,000      |
|Kilimani|3       |150            |Yes    |120,000      |   

### Testing data.  
The testing set is used to evaluate how well the model performs on new, unseen data.    
_Example_    
|Estate  |Bedrooms|House size(sqm)|Parking|
|------  |--------|---------------|-------|
|Umoja   |2       |80             |Yes    |
|Karen   |3       |180            |No     |
|Kilimani|3       |150            |Yes    |

## Recommended folder structure.   

```
my_first_ml_project/
│
├── data/
│   ├── raw.csv               # The original dataset (never edit this directly)
│   └── cleaned.csv           # The data after you clean it
│
├── notebooks/
│   ├── 01_exploration.ipynb  # Looking at the data and making graphs
│   └── 02_model_testing.ipynb# Trying out different ML models
│
├── src/
│   ├── data_cleaning.py      # Python script to clean the data
│   └── train_model.py        # Python script to train the final model
│
├── .gitignore                # Tells Git to hide large data files
├── README.md                 # A short text file explaining your project
└── requirements.txt          # List of libraries to install (pandas, scikit-learn, etc.)```

## 2nd July 2026

## 1. Supervised learning.  
### 1.1 Regression.     
#### 1.1.1 Linear Regression.   
Linear regression is a supervised machine learning algorithm and statistical method used to model the relationship between a dependent(target) variable and one or more independent(predictor) variables.     

Linear regression is like trying to draw a line of best fit through a scatter of dots on a graph.  

_Formula_  
$y = mx + c$   
$y = {\beta_1x} + {\beta_0}$

y = Dependent/Target or the value to be predicted.   
m = gradient or the slope of the curve(how much y changes when x increases by 1).         
x = Independent variable/predictor variable.     
c = y-intercept(the value of y when x is equal to zero where the line crosses y-axis).     

_Example_      
|House size(sqm)(x)|monthly rent(y)|
|------------------|---------------|
|80                |25000          |
|220               |250000         |
|150               |120000         |   


Slope: $\beta_1 = \frac{n\sum XY - (\sum X)(\sum Y)}{n\sum X^2 - (\sum X)^2}$   

Y intercept:  $\beta_0 = \frac{\sum Y - \beta_1\sum X}{n}$

In [13]:
import pandas as pd

data = {'house_size':[80, 220, 150],
        'monthly_rent':[25000, 250000,120000]}

df = pd.DataFrame(data)

# Multiply X and Y
df["xy"] = df["house_size"] * df["monthly_rent"]

# Total of x
sum_house_size = df["house_size"].sum()

# Total of Y
sum_rent = df["monthly_rent"].sum()

# Square X
df["x_squared"] = df["house_size"]**2

print("="*35, "SLOPE", "="*35)
slope = ((len(df) * (df["xy"].sum())) - ((sum_house_size)*(sum_rent)))/((len(df)*(df["x_squared"].sum()))-(sum_house_size**2))

print(slope)
print("="*35, "Y-INTERCEPT", "="*35)
y_intercept = sum_rent - (1607.142857142857 * sum_house_size)/len(df)
print(y_intercept)

=================================== SLOPE ===================================
1607.142857142857
=================================== Y-INTERCEPT ===================================
153928.57142857145


__Types of linear Regression__   
- Simple linear regression.   
- Multiple linear regression.  
- Poynomial regression.  
- Ridge and Lasso regression.  

##### Multiple linear regression.  
Uses two or more predictors.   
_Example_   
Variables:
house size(x1)   
age(x2)     
distance from cbd(x3)    

$y = {\beta_1x_1} + {\beta_2x_2} + {\beta_3x_3} + {\beta_0}$

_Formula_    

$y = {\beta_0} + {\beta_1x_1} + {\beta_2x_2} + {\beta_3x_3} + ....{\beta_nx_n}$    

__Definition of terms in Linear Regression__     
- The regression line: The regression line summarizes the average relationship between x and y. Each point has a predicted value that lies on the line. The line minimizes prediction errors.    
- Intercept:This is the predicted value of Y when x=0.     
- Slope: The slope tells us how much y changes when X increases by one unit.   
_Example_    
sales = 100 + (8 * Advertising)      
Interpretaion: Every additional 1 shilling spent on advertising increases sales by 8 units on average.    

- Residuals(Errors): Residuals = Actual values  predicted values.   
_Formula_   
$Residual = y - \hat{y}$     

- Least Squares Method: The model choose the regression line tht minimizes the sum squared residuals.  Instead of minimizing(which cancels positive and negative errors):     
$\sum({y - \hat{y}})$

Assume we have a dataset with 5 rows:   
|Actual |Predicted |
|-------|----------|
|24     |20        |
|40     |44        | 
|56     |59        |
|70     |67        |  

Errors:   
|Actual |Predicted | Residuals|
|-------|----------|----------|
|24     |20        |4         |
|40     |44        |-4        |
|56     |59        |-3        |
|70     |67        |3         |    

__Note:__ Since adding the errors might hide the actual errors we use the squared errors.    
$\sum(y - \hat{y})^{2}$  

|Actual |Predicted | Residuals|Residualssquared|
|-------|----------|----------|----------------|
|24     |20        |4         |16              |
|40     |44        |-4        |16              |
|56     |59        |-3        |9               |
|70     |67        |3         |9               |    

- Multicollinerity: When two or more independent variables are highly correlated, "They say the same thing to the model" which causes confusion to the model.     
_Example_   
You include bith **weight in kgs** and **weight in pounds** in your model. They're almost perfectly correlated, the model struggles to assign clear influence to each.    

_Effects of multicollinearity_  
Make coefficients unreliable.   
Can lead to overfitting and high variance.    

_Ways to detect multicollinearity_    
1. Correlation Matrix: Check ther correlation between numeric features.   
2. Variance inflation Factor(VIF): A VIF > 5(10) suggests multicollinearity.

In [14]:
# Sum of residuals
errors = 4 + -4 + -3 + 3

print(errors)

# Sum of squared residuals
sq_residuals = 16 + 16 + 9 + 9
print(sq_residuals)

0
50

__Assumptions of Linear Regression__    
These assumptions are essential because violations can lead to biased estimates, incorrect statistical tests, or poor predictions.   
- __Linearity:__ The relationship between predictors and the target should be approximately linear. 
Use scatterplots to check for linearity.    

- __No Multicollinearity(multiple regression):__ Predictors should not be highly correlated with each other.  

- __No influential Outliers:__ Extreme observartions can disproportionally affect the regression line.    

#### Model Evaluation Metrics.    
After building a linear regression model we need to determine how well it performs. Model evaluation metrics compares the model's predicted values with the actual observed values and quantify the prediction error.    
These metrics help us in answering questions such as:    
- How accurate are the predictions.   
- Which regression model performs better?  
- Does the model explain a large proportion of the variation in target variable?   

##### 1.Mean absolute error.   
The mean Absolute Error(MAE) measure the average magnitude of the prediction errors without considering whether the model overestimates(negative error) or underestimates(positive error) the target variable.  
_Formula_    
$MAE=\frac{1}{n}\sum_{i=1}^{n}|y_i-\hat{y}_i|$

Errors:   
|Actual |Predicted | Residuals|absolute error|
|-------|----------|----------|--------------|
|24     |20        |4         |4             |
|40     |44        |-4        |4             |
|56     |59        |-3        |3             |
|70     |67        |3         |3             |  

$MAE = \frac{4 + 4 + 3 + 3}{3}$ = 3.5   

_Advantages_  
- Very easy to understand.   
- Expressed in the same units as the target variable
- Less sensitive to extreme errors than MSE and RMSE.  
- Suitable when all prediction errors should be treated equally.     

_Disadvantages_   
- Does not penalize large errors more heavily than small ones.   
- Two models with the same MAE may have very different error distributions.     

## 6th July 2026

##### 2. Mean Squared Error(MSE)
The mean Square Error(MSE) Calculates the average of the squared prediction errors.    
_Formula_     
$MSE=\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2$    

Because the errors are squared:    
- Large errors contribute much more than smaller ones.    
- Negative errors become positive.  
- Models that make a few very large mistakes(errors) recieve a higher penalty.  

|Prediction error| Squared error |
|----------------|---------------|
|2               |4              |
|3               |9              |
|10              |100            |


Notice that the error of 10 contributes 100 to the MSE, making it influential than the smaller errors.    

__Adantages__    
- Penalizes large prediction errors heavily
- Forms the basis of Ordinary Least Squares(OLS) regression.     

__Disadvantages__.      
- Dificult to interpret because units are squared.     
- Highly sensitive to outliers.     

##### 3. Root Mean Squared Error(RMSE)
The Root Mean Squared Error(RMSE) is the square root of the mean squared error.    
The formula is:     
$RMSE = \sqrt{MSE}$    

The RMSE converts the error back to the original units of the target variable.     
_Example_    
Suppose you were predicting the monthly rent in Nairobi.     
MSE = 1000,000       

then the RMSE:    
$RMSE = \sqrt{1000,000} = 1000$  

If your units were in Shillings this means that the model's prediction differ from the actual values by approximately 1000 Shilling on average.      

_Advantages_      
- Easy to interpret because it has the same units as the target variable.     
- Penalizes large prediction errors.    

_Disadvantages_       
- Sensitive to outliers.    
- Can be heavily influenced by a few extreme prediction errors.       


##### 4. R<sup>2</sup> Score(Coefficient of Determination).    
The R2 Score measures how well the regression model explains the variation in the dependent variable.     
_Formula_       
$R^2=1-\frac{SS_{Residual}}{SS_{Total}}$      

- $SS_{Residual}$ = Sum of Squared Residuals(Unexplained Variation).   
$SS_{res}=\sum (y_{i}-\^{y}_{i})^{2}$

- $SS_{Total}$ = Total sum of Squares(Total variation in the target variable).    
$SS_{tot}=\sum (y_{i}-\={y})^{2}$    

_Example_     

|Actual Values|Predicted Values|
|-------------|----------------|
|2            |2.5             |
|3            |2.0             |
|7            |7.5             |   

Calculate the r2 score.

In [15]:
# Step 1: Calculate the mean of the actual values.    
actual_values = [2, 3, 7]

mean_actual_values = sum(actual_values) / len(actual_values)

# Step II: Calculate the total sum of squares and the residual sum squared  
total_sum_of_squares = ((2-mean_actual_values)**2) + ((3 - mean_actual_values)**2) + ((7 - mean_actual_values)**2)

residual_sum_squared = ((2-2.5)**2) + ((3-2.0)**2) + ((7 - 7.5)**2)

# Step III: Calculate the R2 Score
r2_score = 1 - (residual_sum_squared/total_sum_of_squares)

print("Mean of actual values", mean_actual_values)
print("total_sum_of_squares", total_sum_of_squares)
print("Residual Sum Squared",residual_sum_squared)
print("R2 Score", r2_score)

Mean of actual values 4.0
total_sum_of_squares 14.0
Residual Sum Squared 1.5
R2 Score 0.8928571428571429

A R<sup>2</sup> of 0.89 or 89% means that 89% of the variation in the target variable can be explained by the predictors, while thw remaining 11% is due to factors not captured by the modelor random variation.   

_Interpretations_   
|R<sup>2<\sup>|Interpretation                                                  |
|-------------|----------------------------------------------------------------|
|0.00         |The model explains none of the variation in the target variable | 
|0.40         |The model explains 40% of the variation                         |
|0.75         |The model explains 75% of the variation                         |
|1.0          |Perfect prediction                                              |      

_Advantages_      
- Easy to interpret as a percentage of explained variance.    
- Useful for comparing models built on the same dataset.    
- Provides the overall measure of the model fit.    

_Disadvantages_      
- A high R2 score does not necessarily mean the model is appropriate.    
- Adding more predictors can artificially increase the R2, even if those predictors add little predictive value.    

##### 5. Adjusted R<sup>2</sup>    
The adjusted R<sup>2</sup> improves upon R2 by accounting for the number of predictors in the model.     

Unlike the R2, the adjusted R2 increases only when a new predictor guininely improves the model's performance. If an irrelevant predictor is added, Adjusted R2 may remain unchanged or even decrease.    

_Example_     
Suppose we have two models predicting house prices:     
- __Model A:__ Size, Bedrooms     
- __Model B:__ Size, Bedrooms, House colour.      

House colour is unlikely to influence the house prices. Although adding may slightly increase the R2 value, it provides no meaningful predictive power.     
Adjusted R2 helps identify this by penalizing unnecessary predictors.    

_Advantages_     
- Reduces the risk of overfitting.    
- Better than R2 when comparing models with different number of predictors.    
- Encourages selecting only meaningfulv predictors.     

_Disadvantages._    
- Slightly more difficult to interpret than R2.    


**Note:** A well performing regression model typically has low MAE, Low MSE, low RMSE, and high R<sup>2</sup> and Adjusted R<sup>2
</sup>, while satisfying the assumptions of linear regression.      


## Practical Linear Regression project

### STEP 1: Import relevant libraries and load the dataset.

In [16]:
# Importing libraries.  
import pandas as pd

# Load the dataset.   
salary_df = pd.read_csv("/Users/luxdevhq/Desktop/Data Science CH07/Machine Learning/Supervised_Learning/data/job_salary_prediction_dataset.csv")

salary_df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

### Step 2: Inspecting the dataset, EDA, Hypothesis tests

In [17]:
def basic_checks(df):
    """Checking the summary statistics, basic info, duplicates, null summary"""
    # Check basic info about the dataset
    print("-"*30, "BASIC INFORMATION","-"*30)
    print("\n Basic info", df.info())
    # Check summary statistics
    print("-"*30, "SUMMARY STATISTICS","-"*30)
    print("Summary statistics for numeric columns \n", display(df.describe().T))
    print("Summary statistics for categorical columns \n", display(df.describe().T))
    # Check for duplicates
    print("-"*30, "DUPLICATE SUMMARY","-"*30)
    print("Duplicad rows:",df.duplicated().sum())
    # Check for null summary
    print("-"*30, "NULL SUMMARY","-"*30)
    print("Missing values summary", df.isnull().sum())


basic_checks(salary_df)

------------------------------ BASIC INFORMATION ------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

 Basic info None
------------------------------ SUMMARY STATISTICS ------------------------------

,count,mean,std,min,25%,50%,75%,max
experience_years,250000.0,10.005408,6.060602,0.0,5.0,10.0,15.0,20.0
skills_count,250000.0,9.997812,5.479288,1.0,5.0,10.0,15.0,19.0
certifications,250000.0,2.491928,1.706475,0.0,1.0,2.0,4.0,5.0
salary,250000.0,145718.080524,37407.952729,31867.0,119358.0,143453.0,169492.0,333046.0

Summary statistics for numeric columns
 None

,count,mean,std,min,25%,50%,75%,max
experience_years,250000.0,10.005408,6.060602,0.0,5.0,10.0,15.0,20.0
skills_count,250000.0,9.997812,5.479288,1.0,5.0,10.0,15.0,19.0
certifications,250000.0,2.491928,1.706475,0.0,1.0,2.0,4.0,5.0
salary,250000.0,145718.080524,37407.952729,31867.0,119358.0,143453.0,169492.0,333046.0

Summary statistics for categorical columns
 None
------------------------------ DUPLICATE SUMMARY ------------------------------
Duplicad rows: 0
------------------------------ NULL SUMMARY ------------------------------
Missing values summary job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

## 7th July 2026

In [18]:
categorical_cols = salary_df.select_dtypes(include=[str, 'object']).columns.to_list()
print("Categorical columns \n", categorical_cols)

# Checking for the categorical entries
for column in categorical_cols:
    print("-"*30, column.upper(), "-"*30)
    print(salary_df[column].unique(), "Counts: \n")

Categorical columns
 ['job_title', 'education_level', 'industry', 'company_size', 'location', 'remote_work']
------------------------------ JOB_TITLE ------------------------------
<StringArray>
[              'AI Engineer',              'Data Analyst',
        'Frontend Developer',          'Business Analyst',
           'Product Manager',         'Backend Developer',
 'Machine Learning Engineer',           'DevOps Engineer',
         'Software Engineer',     'Cybersecurity Analyst',
            'Data Scientist',            'Cloud Engineer']
Length: 12, dtype: str Counts:

------------------------------ EDUCATION_LEVEL ------------------------------
<StringArray>
['Bachelor', 'PhD', 'High School', 'Diploma', 'Master']
Length: 5, dtype: str Counts:

------------------------------ INDUSTRY ------------------------------
<StringArray>
[   'Healthcare',       'Telecom',         'Media',        'Retail',
 'Manufacturing',     'Education',       'Finance',    'Technology',
    'Consulting',    'Government']
Length: 10, dtype: str Counts:

------------------------------ COMPANY_SIZE ------------------------------
<StringArray>
['Medium', 'Small', 'Large', 'Enterprise', 'Startup']
Length: 5, dtype: str Counts:

------------------------------ LOCATION ------------------------------
<StringArray>
[      'India',   'Australia',   'Singapore',      'Canada',      'Sweden',
         'USA', 'Netherlands',      'Remote',     'Germany',          'UK']
Length: 10, dtype: str Counts:

------------------------------ REMOTE_WORK ------------------------------
<StringArray>
['Hybrid', 'No', 'Yes']
Length: 3, dtype: str Counts:

In [22]:
# Identify the numerical columns.  
numerical_cols = salary_df.select_dtypes(include=[int, float]).columns.to_list()

numerical_cols.remove("salary")
print(numerical_cols)

['experience_years', 'skills_count', 'certifications']

In [20]:
salary_df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

### STEP 3: Separate features and the target.

In [24]:
X = salary_df.drop(columns=["salary"]) # Predictors or the features
y = salary_df["salary"] # Target column

print("X features", display(X.head()))
print("y Target", display(y.head()))

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0

X features None

0    109413
1     93764
2    148123
3    189123
4    165069
Name: salary, dtype: int64

y Target None

- X contains the input columns/Features
- y contains the answer/target we want the model to predict

### STEP 4: Split the data to train and test.   
When building a machine learning model, we should not train and test the model usig the same data. We split the data into two main parts:     
__Training Set__    
The training set is the data used to teach the machine learning model.   
The model studies this data and learns patterns from it.     

X_train, y_train, X_test, y_test      

Where:    
`X_train` = Input features used for training.    
`y_train` = correct answers/labels for training.    

_Why do we split the data?_       
We split the data to check whether the model can generalize.    
Generalization means the model can perform well on new, unseen data, not just the data it memorized during training.       

Common train-tests include => 80% training: 20% testing, 70% training and 30% testing.

In [27]:
# Splitting the data.  
from sklearn.model_selection import train_test_split   

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Xtrain length", len(X_train))
print("X test length", len(X_test))

Xtrain length 200000
X test length 50000

### STEP 5: Encoding the categorical columns.
Machine Learning models work mainly with numbers, not raw text.    
When we have categorical columns such as, education_level, industry, gender etc we must convert them into numerical from. Without encoding, many ML models will throw an error or fail to train properly.     

##### Types of Encoders in Machine learning.     
__1. Label Encoder__.    
Label encoding converts each category into a unique number.     

_Example_    
|City.   |Encoded city|
|--------|------------|
|Nairobi |0           |
|Kisumu  |1           |
|Mombasa |2           |
|Nakuru  |3           |   

```python
from sklearn.preprocessing import LabelEncoder  

encoder = LabelEncoder()

df["Gender_encoded"] = encoder.fit_transform(df["Gender"])
```
_Advantages_  
- Simple and easy to use
- Does not create many columns 

_Disadvantages_  
- The model may assume there is a ranking between categories.  
For example, if Nairobi = 0, Kisumu = 1, Mombasa = 2, the model might think Mombasa is greater than Kisumu and Nairobi which may not be meaningful.    

_Best use case_   
Best used for target labels e.g when target is where an email is spam or not spam.   

__2. One-hot Encoding__     
One-hot encoding creates a new column for each category.     
Each row gets a value of 1 if the category is present and 0 if it is not.    

_Example_   
|City.  |
|-------|
|Nairobi|
|Kisumu |
|Mombasa|
|Nairobi|   

After OneHot Encoding:  
|City_Nairobi|City_Kisumu|City_Mombasa|
|------------|-----------|------------|
|1           |0          |0           |
|0           |1          |0           |
|0           |0          |1           |
|1           |0          |0           |   

```python 
from sklearn.preprocessing import OneHotEncoder

encoder =OneHotEncoder()

encoded_data = encoder.fit_transform(df[["City"]])  
```

```python
df_encoded = pd.get_dummies(df, columns = ["City"])
```

_Advantages_   
- Does not create false rankings between categories 
- Works well with algorithms like linear regression.  
- Very useful for nominal data.   

_Disadvantages_  
- Can create many columns if the feature has many unique categories, this can make the dataset large and hard to train. This problem is called __High Dimensionality__   

_Best use case_  
Use one-hot encoding for categorical columns with no natural order e.g city, gender county, department product category.   

__3. Ordinal Encoding__     
Ordinal encoding is used when categories have a meaningful order.    

_Example_   
|Education Level| Encoded value|
|---------------|--------------|
|Primary        |1             |
|High School    |2             |
|Diploma        |3             |
|Degree         |4             |
|Masters        |5             |
|PhD            |6             |     

Here, the order matters because masters is higher than Degree, Degree is higher than Diploma and so on.     
```python 
from sklearn.preprocessing import OrdinalEncoder  

encoder = OrdinalEncoder(categories=[[
    'Primary','High School', 'Diploma', 'Degree', 'Masters', 'PhD'
]])  

df['Education_encoded'] = encoder.fit_transform(df[["Education"]])
```  
_Advantages_    
- Preserves order of the categories
- Uses only one column
- Good for ordered categories.     

_Disadvantages_     
- Can be misleading if used on categories tha do not have a real order.   
- The model may assume the distance between categories is equal.  
for example, the difference between Primary and High School may not be the same as the difference between Degree and masters.    

_Best use Case_  
Use Ordinal encoding when the categories have a clear order.    

##### __Other encoding__  
- __4. Binary Encoding__   
Binary encoding first converts categories into numbers, then converts those numbers into binary form.    

_Example_    
|Category |Number |Binary |
|---------|-------|-------|
|Nairobi. |1      |001    |
|Kisumu   |2      |010    |
|Mombasa. |3      |011    |
|Eldoret  |4      |100    |   

- __5. Frequency encoding__  
Frequency encoding replaces each category with how often it appears in the dataset.   

|City   |Frequency |
|-------|----------|
|Nairobi|50        |
|Kisumu |20        |
|Mombasa|30        |   

If Nairobi appears 50 times, every Nairobi Value is replaced with 50. 

_Disadvantages_   
- Different categories can have the same frequency.  
- It may lose important category identity.   
- The model only learns how common a category is, not what that category represents.   

- __6. Target/Mean Encoding__   
Target encoding replaces each category with the average target value for that category.   

_Example_   
Assume we are predicting whether a customer will buy a product.   

|City   |Average purchase rate|
|-------|---------------------|
|Nairobi|0.75                 |
|Kisumu |0.40                 |
|Mombasa|0.60                 |     

So Nairobi may be replaced by 0.75.

In [30]:
# Encode the training set.   
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True, dtype=int) 

# Encoding the testing set.  
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True, dtype=int)

In [31]:
print(display(X_train_encoded.head()))

,experience_years,skills_count,certifications,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,...,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
75381,4,14,5,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
65569,1,6,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
163473,16,3,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
90518,4,18,4,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
138866,7,8,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0

None

### STEP 6: Train the Linear Regression Model

In [32]:
# Load the relevant module
from sklearn.linear_model import LinearRegression  

# Instantiate the model    
model = LinearRegression()

# Fit or train the model
model.fit(X_train_encoded, y_train)

LinearRegression()

### Step 7: Make Predictions

In [34]:
y_pred = model.predict(X_test_encoded)

In [35]:
results = pd.DataFrame({"Actual Salary(y_test)":y_test.values,
                        "Predicted salary(y_pred)":y_pred})

results.head(50)

    Actual Salary(y_test)  Predicted salary(y_pred)
0                  164009             172850.850756
1                   79594              89234.518210
2                   74090              63791.555801
3                  177193             168311.830872
4                  120012             117222.932453
5                  163369             171755.346547
6                  111889             110424.893725
7                   75418              60449.433244
8                  103067              93094.305457
9                  190692             192448.961434
10                 114616             123707.730708
11                 213768             207106.600957
12                 126256             130773.107307
13                  99105             102119.811665
14                 277977             256477.397701
15                 153683             158574.795479
16                 235839             227035.232178
17                 149179             150293.644955
18                 130145             129564.640351
19                 171868             174959.096288
20                 176316             174956.150355
21                 151573             147226.742697
22                  85155              76691.328616
23                 211079             207925.198982
24                 193655             191664.785677
25                 174809             176091.695994
26                 110007             103849.557120
27                 125885             115542.391424
28                 210860             201989.157255
29                 112184             107372.253788
30                 174141             168937.226337
31                 136760             141952.517451
32                 215145             203905.419099
33                 217694             215282.547298
34                 160372             165861.711703
35                 150228             148630.355954
36                 109413             111413.859361
37                 139571             145420.819379
38                 103811             107568.999396
39                 147598             148300.540224
40                 110254             113119.144220
41                 130462             133599.263261
42                 162248             160659.639720
43                 177206             172375.203703
44                 178303             181997.816959
45                 115045             108590.828125
46                 157499             163156.461539
47                 177966             175074.641800
48                  85243              79672.781043
49                  94452             100389.512453

### STEP 8: Evaluate the model

In [36]:
# Loading relevant modules
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error: ", round(mae, 2))
print("Mean Squared Error: ", round(mse, 2))
print("Root Mean Squared Error: ", round(rmse, 2))
print("Coefficient of Determination R2: ", round(r2, 4))

Mean Absolute Error:  5436.1
Mean Squared Error:  50773076.66
Root Mean Squared Error:  7125.52
Coefficient of Determination R2:  0.9635